### ISSUE TITLE
run create_data.py  error

### ISSUE THREAD

**Issue by Shaoqing26** [SmallMunich/nutonomy_pointpillars#8]
Traceback (most recent call last):
  File "/media/buaa/MyPassport/Deeplidar/nutonomy_pointpillars/second/core/non_max_suppression/nms_cpu.py", line 11, in <module>
    from second.core.non_max_suppression.nms import (
ImportError: **/media/buaa/MyPassport/Deeplidar/nutonomy_pointpillars/second/core/non_max_suppression/nms.so: cannot open shared object file: No such file or directory**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create_data.py", line 12, in <module>
    from second.core import box_np_ops
  File "/media/buaa/MyPassport/Deeplidar/nutonomy_pointpillars/second/core/box_np_ops.py", line 7, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/media/buaa/MyPassport/Deeplidar/nutonomy_pointpillars/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/media/buaa/MyPassport/Deeplidar/nutonomy_pointpillars/second/core/non_max_suppression/nms_cpu.py", line 19, in <module>
    cuda=True)
  File "/media/buaa/MyPassport/Deeplidar/nutonomy_pointpillars/second/utils/buildtools/pybind11_build.py", line 96, in load_pb11
    cmds.append(Nvcc(s, out(s), arch))
  File "/media/buaa/MyPassport/Deeplidar/nutonomy_pointpillars/second/utils/buildtools/command.py", line 123, in __init__
    raise ValueError("you must specify arch if use cuda.")
**ValueError: you must specify arch if use cuda.**

I met this problems when i run create_data.py  on Xavier,Can u help me solve this problems?

**Comment by SmallMunich** [comment]
why use create_data.py in xavier? inference process do not need this file.

**Comment by Shaoqing26** [comment]
> why use create_data.py in xavier? inference process do not need this file.

I want test the project  Velo and acc on Xavier，but It occor this problem， I contacted you on CSDN，Maybe you dont get the messege

**Comment by Shaoqing26** [comment]
> why use create_data.py in xavier? inference process do not need this file.

I am a BUAA sutdent ,May I have your kindly advice? I have send you My Wechat account(12042003) on CSDN，Can I have your number？Its appreciate you can add me later.

**Comment by SmallMunich** [comment]
> > why use create_data.py in xavier? inference process do not need this file.
> 
> I want test the project Velo and acc on Xavier，but It occor this problem， I contacted you on CSDN，Maybe you dont get the messege

Sorry, I didn't read the blog in time, I have replied to you justly.

**Comment by xieqi1996** [comment]
> > why use create_data.py in xavier? inference process do not need this file.
> 
> I am a BUAA sutdent ,May I have your kindly advice? I have send you My Wechat account(12042003) on CSDN，Can I have your number？Its appreciate you can add me later.

Have you solved the problem？
